---
  name: "GeoTag-X Sample Project"
  short_name: "sample"
  description: "A sample GeoTag-X project."
  why: "This is a simple project that highlights GeoTag-X's features."
  questionnaire:
    -
      key: "isWaterVisible"
      type: "binary"
      question:
        en: "Can you see any water in the photo?"
        fr: "Can you see any water in the photo? (FR)"
      hint:
        en: "More specifically, can you see small water bodies like puddles, or large ones such as rivers or lakes?"
        fr: "More specifically, can you see small water bodies like puddles, or large ones such as rivers or lakes? (FR)"
      branch:
        yes: "waterColor"
        no: "name"
    -
      key: "waterColor"
      type: "select"
      question:
        en: "What color is the water?"
        fr: "What color is the water? (FR)"
      parameters:
        options:
          -
            label:
              en: "Red"
              fr: "Red (FR)"
            value: "Red"
          -
            label:
              en: "Aqua Blue"
              fr: "Aqua Blue (FR)"
            value: "AquaBlue"
          -
            label:
              en: "Green"
              fr: "Green (FR)"
            value: "Green"
          -
            label:
              en: "Orange"
              fr: "Orange (FR)"
            value: "Orange"
    -
      key: "smallPoolsOfWaterVisible"
      type: "binary"
      question:
        en: "Can you see small pools of water?"
        fr: "Can you see small pools of water? (FR)"
      branch:
        no: "largeBodyOfWaterVisible"
    -
      key: "smallPoolsOfWaterNearShelters"
      type: "binary"
      question:
        en: "Are these small pools of water near human shelters or a settlement?"
        fr: "Are these small pools of water near human shelters or a settlement? (FR)"
      branch: "name"
    -
      key: "largeBodyOfWaterVisible"
      type: "binary"
      question:
        en: "Can you see a large body of water?"
        fr: "Can you see a large body of water? (FR)"
    -
      key: "name"
      type: "text"
      question:
        en: "Please enter your name"
        fr: "Please enter your name (FR)"
      parameters:
        placeholder:
          en: "A fake name will do"
          fr: "A fake name will do (FR)"
